export const _SCHOOL_GIRL = {
  defoult: {
    attack: {
      sprite: './img/characters/schoolGirl/defoultSkin/Attack.png',
      totalFrames: 8,
      fps: 8,
    },
    dialogue: {
      sprite: './img/characters/schoolGirl/defoultSkin/Dialogue.png',
      totalFrames: 11,
      fps: 8,
    },
    idle: {
      sprite: './img/characters/schoolGirl/defoultSkin/Idle.png',
      totalFrames: 9,
      fps: 8,
    },
    walk: {
      sprite: './img/characters/schoolGirl/defoultSkin/Walk.png',
      totalFrames: 12,
      fps: 17,
    },
    protect: {
      sprite: './img/characters/schoolGirl/defoultSkin/Protection.png',
      totalFrames: 4,
      fps: 8,
    },
    logo: './img/characters/schoolGirl/defoultSkin/heroIco.png',
    skinChangeText: 'первая тяночка на раене!',
    count: 0,
  },
  skinTwo: {
    attack: {
      sprite: './img/characters/schoolGirl/skinTwo/Attack.png',
      totalFrames: 9,
      fps: 8,
      endFrame: 6,
    },
    dialogue: {
      sprite: './img/characters/schoolGirl/skinTwo/Dialogue.png',
      totalFrames: 6,
      fps: 8,
    },
    idle: {
      sprite: './img/characters/schoolGirl/skinTwo/Idle.png',
      totalFrames: 7,
      fps: 7,
    },
    walk: {
      sprite: './img/characters/schoolGirl/skinTwo/Walk.png',
      totalFrames: 12,
      fps: 17,
    },
    protect: {
      sprite: './img/characters/schoolGirl/skinTwo/Protection.png',
      totalFrames: 2,
      fps: 8,
    },
    logo: './img/characters/schoolGirl/skinTwo/heroIco.png',
    skinChangeText: 'Пионер всегда готов!',
    count: 1,
  },
  skinThree: {
    attack: {
      sprite: './img/characters/schoolGirl/skinThree/Attack.png',
      totalFrames: 6,
      fps: 8,
      endFrame: 1,
    },
    dialogue: {
      sprite: './img/characters/schoolGirl/skinThree/Dialogue.png',
      totalFrames: 5,
      fps: 8,
    },
    idle: {
      sprite: './img/characters/schoolGirl/skinThree/Idle.png',
      totalFrames: 6,
      fps: 7,
    },
    walk: {
      sprite: './img/characters/schoolGirl/skinThree/Walk.png',
      totalFrames: 12,
      fps: 17,
    },
    protect: {
      sprite: './img/characters/schoolGirl/skinThree/Protection.png',
      totalFrames: 3,
      fps: 8,
    },
    logo: './img/characters/schoolGirl/skinThree/heroIco.png',
    skinChangeText: 'опа, бабулин гардероб!',
    count: 2,
  },
}
export const _SATYR = {
  defoult: {
    attack: {
      sprite: './img/characters/satyr/defoultSkin/Attack.png',
      totalFrames: 4,
      fps: 8,
    },
    dead: {
      sprite: './img/characters/satyr/defoultSkin/Dead.png',
      totalFrames: 4,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/satyr/defoultSkin/Idle.png',
      totalFrames: 7,
      fps: 8,
    },
    walk: {
      sprite: './img/characters/satyr/defoultSkin/Walk.png',
      totalFrames: 12,
      fps: 17,
    },
    protect: {
      sprite: './img/characters/satyr/defoultSkin/Protection.png',
      totalFrames: 4,
      fps: 8,
    },
    logo: './img/characters/satyr/defoultSkin/heroIco.png',
    skinChangeText: 'Во имя света!',
    count: 0,
    dead: './img/characters/satyr/dead.png',
  },
  skinTwo: {
    attack: {
      sprite: './img/characters/satyr/skinTwo/Attack.png',
      totalFrames: 8,
      fps: 8,
      endFrame: 6,
    },
    dead: {
      sprite: './img/characters/satyr/skinTwo/Dead.png',
      totalFrames: 4,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/satyr/skinTwo/Idle.png',
      totalFrames: 7,
      fps: 7,
    },
    walk: {
      sprite: './img/characters/satyr/skinTwo/Walk_normalized.png',
      totalFrames: 12,
      fps: 15,
    },
    protect: {
      sprite: './img/characters/satyr/skinTwo/Protection.png',
      totalFrames: 4,
      fps: 5,
    },
    logo: './img/characters/satyr/skinTwo/heroIco.png',
    skinChangeText: 'Природа - наш храм!',
    count: 1,
  },
}
export const _VAMPIRE = {
  defoult: {
    attack: {
      sprite: './img/characters/vampire/defoultSkin/Attack_1.png',
      totalFrames: 5,
      fps: 8,
    },
    dead: {
      sprite: './img/characters/vampire/defoultSkin/Dead.png',
      totalFrames: 10,
      fps: 14,
    },
    idle: {
      sprite: './img/characters/vampire/defoultSkin/Idle.png',
      totalFrames: 5,
      fps: 7,
    },
    walk: {
      sprite: './img/characters/vampire/defoultSkin/Run.png',
      totalFrames: 6,
      fps: 7,
    },
    protect: {
      sprite: './img/characters/vampire/defoultSkin/Hurt.png',
      totalFrames: 2,
      fps: 5,
    },
    logo: './img/characters/vampire/defoultSkin/heroIco.png',
    skinChangeText: 'Темнота зовет!',
    count: 0,
  },
  skinTwo: {
    attack: {
      sprite: './img/characters/vampire/skinTwo/Attack_1.png',
      totalFrames: 6,
      fps: 8,
      endFrame: 4,
    },
    dead: {
      sprite: './img/characters/vampire/skinTwo/Dead.png',
      totalFrames: 8,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/vampire/skinTwo/Idle.png',
      totalFrames: 5,
      fps: 7,
    },
    walk: {
      sprite: './img/characters/vampire/skinTwo/Walk.png',
      totalFrames: 6,
      fps: 9,
    },
    protect: {
      sprite: './img/characters/vampire/skinTwo/Hurt.png',
      totalFrames: 2,
      fps: 5,
    },
    logo: './img/characters/vampire/skinTwo/heroIco.png',
    skinChangeText: 'Спи спокойно, смертный.',
    count: 1,
  },
}
export const _GORGON = {
  defoult: {
    attack: {
      sprite: './img/characters/gorgon/defoultSkin/Attack_3.png',
      totalFrames: 10,
      fps: 8,
      endFrame: 4,
    },
    dead: {
      sprite: './img/characters/gorgon/defoultSkin/Dead.png',
      totalFrames: 3,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/gorgon/defoultSkin/Idle.png',
      totalFrames: 7,
      fps: 8,
    },
    walk: {
      sprite: './img/characters/gorgon/defoultSkin/Run.png',
      totalFrames: 7,
      fps: 8,
    },
    protect: {
      sprite: './img/characters/gorgon/defoultSkin/Hurt.png',
      totalFrames: 3,
      fps: 5,
    },
    logo: './img/characters/gorgon/defoultSkin/heroIco.png',
    skinChangeText: 'Змеи вместо волос.',
    count: 0,
  },
  skinTwo: {
    attack: {
      sprite: './img/characters/gorgon/skinTwo/Attack_3.png',
      totalFrames: 10,
      fps: 8,
      endFrame: 4,
    },
    dead: {
      sprite: './img/characters/gorgon/skinTwo/Dead.png',
      totalFrames: 3,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/gorgon/skinTwo/Idle.png',
      totalFrames: 7,
      fps: 8,
    },
    walk: {
      sprite: './img/characters/gorgon/skinTwo/Run.png',
      totalFrames: 7,
      fps: 8,
    },
    protect: {
      sprite: './img/characters/gorgon/skinTwo/Hurt.png',
      totalFrames: 3,
      fps: 5,
    },
    logo: './img/characters/gorgon/skinTwo/heroIco.png',
    skinChangeText: 'Ужас, застывший в камне!',
    count: 1,
  },
  skinThree: {
    attack: {
      sprite: './img/characters/gorgon/skinThree/Attack_2.png',
      totalFrames: 10,
      fps: 8,
      endFrame: 4,
    },
    dead: {
      sprite: './img/characters/gorgon/skinThree/Dead.png',
      totalFrames: 3,
      fps: 5,
    },
    idle: {
      sprite: './img/characters/gorgon/skinThree/Idle.png',
      totalFrames: 7,
      fps: 8,
    },
    walk: {
      sprite: './img/characters/gorgon/skinThree/Run.png',
      totalFrames: 7,
      fps: 8,
    },
    protect: {
      sprite: './img/characters/gorgon/skinThree/Hurt.png',
      totalFrames: 3,
      fps: 5,
    },
    logo: './img/characters/gorgon/skinThree/heroIco.png',
    skinChangeText: 'Посмотри на меня!',
    count: 2,
  },
}

export const _CHARS = [
  {
    id: 'school_girl',
    name: 'School girl',
    index: 0,
    skins: _SCHOOL_GIRL,
    class: 'hero-container',
    text: 'Не буду учится!',
    data: {
      hp: 110,
      maxHp: 110,
      mana: 100,
      maxMana: 100,
      damage: 20,
      manaRegen: 5,
    },
    spells: [
      {
        name: 'Basic',
        damage: 10,
        school: 'fire',
        manacost: 0,
        ico: './img/effects/heroSpells/spellIco/arcane-sceptre.png',
        desc: 'Обычная атака посохом.',
      },
      {
        name: 'Fireboll',
        damage: 24,
        school: 'fire',
        manacost: 20,
        ico: './img/effects/heroSpells/spellIco/explosion-3.png',
        desc: 'Выпускает огненный шар в цель. Стоит 20 маны.',
      },
      {
        name: 'Inferno',
        damage: 45,
        school: 'fire',
        manacost: 50,
        ico: './img/effects/heroSpells/spellIco/meteor.png',
        desc: 'Обруишвает на врага Инферно.Стоит 50 маны.',
      },
      {
        name: 'Curse',
        damage: 5,
        school: 'Shadow',
        manacost: 30,
        ico: './img/effects/heroSpells/spellIco/curse.png',
        desc: 'Проклинает врага на -20% урона. Стоит 30 маны.',
      },
      {
        name: 'Heal',
        damage: 2,
        school: 'Holy',
        manacost: 45,
        ico: './img/effects/heroSpells/spellIco/buff.png',
        desc: 'Вы лечите себя на 50 единиц оверхилом. Стоит 45 маны.',
      },
    ],
  },
  {
    id: 'satyr',
    name: 'Satyr',
    index: 1,
    skins: _SATYR,
    class: 'hero-container',
    text: 'Прыг скок...',
    spells: [
      {
        name: 'Basic',
        damage: 10,
        school: 'fire',
        manacost: 0,
        ico: './img/effects/heroSpells/spellIco/arcane-sceptre.png',
        desc: 'Обычная атака посохом.',
      },
      {
        name: 'Fireboll',
        damage: 24,
        school: 'fire',
        manacost: 20,
        ico: './img/effects/heroSpells/spellIco/explosion-3.png',
        desc: 'Выпускает огненный шар в цель. Стоит 20 маны.',
      },
      {
        name: 'Inferno',
        damage: 45,
        school: 'fire',
        manacost: 50,
        ico: './img/effects/heroSpells/spellIco/meteor.png',
        desc: 'Обруишвает на врага Инферно.Стоит 50 маны.',
      },
      {
        name: 'Curse',
        damage: 5,
        school: 'Shadow',
        manacost: 30,
        ico: './img/effects/heroSpells/spellIco/curse.png',
        desc: 'Проклинает врага на -20% урона. Стоит 30 маны.',
      },
      {
        name: 'Heal',
        damage: 2,
        school: 'Holy',
        manacost: 45,
        ico: './img/effects/heroSpells/spellIco/buff.png',
        desc: 'Вы лечите себя на 50 единиц оверхилом. Стоит 45 маны.',
      },
    ],
    data: {
      hp: 100,
      maxHp: 100,
      mana: 150,
      maxMana: 150,
      damage: 15,
      manaRegen: 6,
    },
  },
  {
    id: 'vampire',
    name: 'Vampire',
    index: 2,
    skins: _VAMPIRE,
    class: 'hero-container',
    text: 'Пора на охоту!',
    spells: [
      {
        name: 'Basic',
        damage: 10,
        school: 'fire',
        manacost: 0,
        ico: './img/effects/heroSpells/spellIco/arcane-sceptre.png',
        desc: 'Обычная атака посохом.',
      },
      {
        name: 'Fireboll',
        damage: 24,
        school: 'fire',
        manacost: 20,
        ico: './img/effects/heroSpells/spellIco/explosion-3.png',
        desc: 'Выпускает огненный шар в цель. Стоит 20 маны.',
      },
      {
        name: 'Inferno',
        damage: 45,
        school: 'fire',
        manacost: 50,
        ico: './img/effects/heroSpells/spellIco/meteor.png',
        desc: 'Обруишвает на врага Инферно.Стоит 50 маны.',
      },
      {
        name: 'Curse',
        damage: 5,
        school: 'Shadow',
        manacost: 30,
        ico: './img/effects/heroSpells/spellIco/curse.png',
        desc: 'Проклинает врага на -20% урона. Стоит 30 маны.',
      },
      {
        name: 'Heal',
        damage: 2,
        school: 'Holy',
        manacost: 45,
        ico: './img/effects/heroSpells/spellIco/buff.png',
        desc: 'Вы лечите себя на 50 единиц оверхилом. Стоит 45 маны.',
      },
    ],
    data: {
      hp: 140,
      maxHp: 140,
      mana: 70,
      maxMana: 70,
      damage: 25,
      manaRegen: 10,
    },
  },
  {
    id: 'gorgon',
    name: 'Gorgon',
    index: 3,
    skins: _GORGON,
    class: 'hero-container',
    text: 'Пшш-шшш!',
    spells: [
      {
        name: 'Basic',
        damage: 10,
        school: 'fire',
        manacost: 0,
        ico: './img/effects/heroSpells/spellIco/arcane-sceptre.png',
        desc: 'Обычная атака посохом.',
      },
      {
        name: 'Fireboll',
        damage: 24,
        school: 'fire',
        manacost: 20,
        ico: './img/effects/heroSpells/spellIco/explosion-3.png',
        desc: 'Выпускает огненный шар в цель. Стоит 20 маны.',
      },
      {
        name: 'Inferno',
        damage: 45,
        school: 'fire',
        manacost: 50,
        ico: './img/effects/heroSpells/spellIco/meteor.png',
        desc: 'Обруишвает на врага Инферно.Стоит 50 маны.',
      },
      {
        name: 'Curse',
        damage: 5,
        school: 'Shadow',
        manacost: 30,
        ico: './img/effects/heroSpells/spellIco/curse.png',
        desc: 'Проклинает врага на -20% урона. Стоит 30 маны.',
      },
      {
        name: 'Heal',
        damage: 2,
        school: 'Holy',
        manacost: 45,
        ico: './img/effects/heroSpells/spellIco/buff.png',
        desc: 'Вы лечите себя на 50 единиц оверхилом. Стоит 45 маны.',
      },
    ],
    data: {
      hp: 170,
      maxHp: 170,
      mana: 110,
      maxMana: 110,
      damage: 22,
      manaRegen: 8,
    },
  },
]
